#omni_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  first_wheel_controller:
    type     : velocity_controllers/JointVelocityController
    joint    : first_wheel_joint
    publish_rate: 50
    pid: {p: 10.0, i: 1.0, d: 0.0}

  second_wheel_controller:
    type     : velocity_controllers/JointVelocityController
    joint    : second_wheel_joint
    publish_rate: 50
    pid: {p: 10.0, i: 1.0, d: 0.0}

  third_wheel_controller:
    type     : velocity_controllers/JointVelocityController
    joint    : third_wheel_joint
    publish_rate: 50
    pid: {p: 10.0, i: 1.0, d: 0.0}

  camera_bracket_controller:
    type     : position_controllers/JointPositionController
    joint    : main_camera_bracket_joint
    publish_rate: 50
    pid: {p: 10.0, i: 1.0, d: 0.0}
